# Create the stateful pods
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
      app.kubernetes.io/name: mysql
  serviceName: mysql
  replicas: 3
#  template:
#    spec:
#      volumes:
#        - name: data
#          persistentVolumeClaim:
#            claimName: csi-pvc-cinderplugin
#            readOnly: false
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
        storageClassName: csi-sc-cinderplugin