apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patchesStrategicMerge:
- deployment.yaml

patches:
- path: patch_removeTemplates.yaml
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: mysql

resources:
- cinder.yaml