apiVersion: ${INGRESS_API_VERSION}
kind: Ingress
metadata:
  name: kubex
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: ${HOST}
      http:
        paths:
          - path: /
            backend:
              serviceName: kubex
              servicePort: 80