apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubex.fullname" . }}
  namespace: default
data:
  FLASK_PORT: "{{ .Values.kubex.flask.port }}"
  FLASK_DEBUG: "{{ .Values.kubex.flask.debug }}"
  SVC: "{{ .Values.kubex.mysql_service }}"
  SQLALCHEMY_DATABASE_URI: "{{ .Values.kubex.sqlalchemy.uri }}"
  SQLALCHEMY_DATABASE_URI_READONLY: "{{ .Values.kubex.sqlalchemy.uri_readonly }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubex.fullname" . }}-flask-nginx
  namespace: default
data:
  default.conf: |
    server {
        listen 80;

        server_name _;

        location ~ \.(css|js|jpg|png|jpeg|webp|gif|svg) {
            root /app/public;
        }

        location / {
            proxy_set_header Host $host ;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto: http;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_pass http://127.0.0.1:8080;
            proxy_read_timeout 10;
        }
    }