apiVersion: v1
kind: ConfigMap
metadata:
  name: kubex
  namespace: default
data:
  FLASK_PORT: "${FLASK_PORT}"
  FLASK_DEBUG: "${FLASK_DEBUG}"
  SQLALCHEMY_DATABASE_URI: "${SQLALCHEMY_DATABASE_URI}"
  SQLALCHEMY_DATABASE_URI_READONLY: "${SQLALCHEMY_DATABASE_URI_READONLY}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-nginx
  namespace: default
data:
  default.conf: |
    server {
        listen 80;

        server_name _;

        location ~ \.(css|js|jpg|png|jpeg|webp|gif|svg) {
            root /app/public;
        }

        location / {
            proxy_set_header Host $host ;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto: http;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_pass http://127.0.0.1:8080;
            proxy_read_timeout 10;
        }
    }